 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stations", type: :request do
  
  # Station. As you add validations to Station, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Station.create! valid_attributes
      get stations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      station = Station.create! valid_attributes
      get station_url(station)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_station_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      station = Station.create! valid_attributes
      get edit_station_url(station)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Station" do
        expect {
          post stations_url, params: { station: valid_attributes }
        }.to change(Station, :count).by(1)
      end

      it "redirects to the created station" do
        post stations_url, params: { station: valid_attributes }
        expect(response).to redirect_to(station_url(Station.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Station" do
        expect {
          post stations_url, params: { station: invalid_attributes }
        }.to change(Station, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post stations_url, params: { station: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested station" do
        station = Station.create! valid_attributes
        patch station_url(station), params: { station: new_attributes }
        station.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the station" do
        station = Station.create! valid_attributes
        patch station_url(station), params: { station: new_attributes }
        station.reload
        expect(response).to redirect_to(station_url(station))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        station = Station.create! valid_attributes
        patch station_url(station), params: { station: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested station" do
      station = Station.create! valid_attributes
      expect {
        delete station_url(station)
      }.to change(Station, :count).by(-1)
    end

    it "redirects to the stations list" do
      station = Station.create! valid_attributes
      delete station_url(station)
      expect(response).to redirect_to(stations_url)
    end
  end
end
